---
prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  issues: []
  prs:
    - key: c
      command: >
        tmux new-window -c {{.RepoPath}} '
          gh pr checkout {{.PrNumber}} &&
          svim -c ":DiffviewOpen main...{{.HeadRefName}}"
        '
    - key: v
      command: >
        cd {{.RepoPath}} &&
        gt get {{.HeadRefName}} &&
        svim
repoPaths:
  :owner/:repo: ~/Projects/:repo
theme:
  ui:
    table:
      showSeparator: false
# Mocha Mauve:
  colors:
    text:
      primary: '#cdd6f4'
      secondary: '#cba6f7'
      inverted: '#11111b'
      faint: '#bac2de'
      warning: '#f38ba8'
      success: '#a6e3a1'
    background:
      selected: '#313244'
    border:
      primary: '#cba6f7'
      secondary: '#45475a'
      faint: '#313244'
pager:
  diff: ''
confirmQuit: false
