# vim:set ft=tmux:

# Unset all variables so that they can be set again:
# Main
set -ug @thm_background
set -ug @thm_text

# Colors
set -ug @thm_violet
set -ug @thm_pink
set -ug @thm_red
set -ug @thm_yellow
set -ug @thm_orange
set -ug @thm_green
set -ug @thm_teal
set -ug @thm_blue

# Surfaces
set -ug @thm_subtext
set -ug @thm_dimmed
set -ug @thm_surface_1
set -ug @thm_surface_0
