[colors]
ansi = [
  '{{surface1}}',
  '{{red}}',
  '{{green}}',
  '{{yellow}}',
  '{{blue}}',
  '{{pink}}',
  '{{teal}}',
  '{{subtext1}}',
]
background = '{{base}}'
brights = [
  '{{surface2}}',
  '{{red}}',
  '{{green}}',
  '{{yellow}}',
  '{{blue}}',
  '{{pink}}',
  '{{teal}}',
  '{{subtext0}}',
]
compose_cursor = '{{flamingo}}'
cursor_bg = '{{mauve}}'
cursor_border = '{{mauve}}'
cursor_fg = '{{crust}}'
foreground = '{{text}}'
scrollbar_thumb = '{{surface2}}'
selection_bg = '{{surface1}}'
selection_fg = '{{text}}'
split = '{{overlay0}}'
visual_bell = '{{surface0}}'

[colors.indexed]
16 = '{{peach}}'
17 = '{{rosewater}}'

[colors.tab_bar]
background = '{{crust}}'
inactive_tab_edge = '{{surface0}}'

[colors.tab_bar.active_tab]
bg_color = '{{mauve}}'
fg_color = '{{crust}}'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '{{mantle}}'
fg_color = '{{text}}'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '{{base}}'
fg_color = '{{text}}'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '{{surface0}}'
fg_color = '{{text}}'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '{{surface1}}'
fg_color = '{{text}}'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'schemar'
name = '{{name}}'
