# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-a5e2bda5-7155-4656-a4c8-20ef2777452c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-a5e2bda5-7155-4656-a4c8-20ef2777452c".device = "/dev/disk/by-uuid/a5e2bda5-7155-4656-a4c8-20ef2777452c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/703C-4EF1";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-16752042-d157-4157-9cfe-f154101e7d55"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
