#+title: Emacs settings file

* Basics
** Undo/Redo
Use the undo-fu package to not have Emacs' confusing undo/redo functionality.
Also required by evil for redo-functionality.
#+BEGIN_SRC emacs-lisp
  (use-package undo-fu)
#+END_SRC
* Evil Mode
  Re-map the default universal argument from ~C-u~ to ~C-f~.
  ~C-u~ is used by evil mode to scroll up half a screen.
  #+BEGIN_SRC emacs-lisp
    (define-key global-map (kbd "C-f") 'universal-argument)
    (define-key universal-argument-map (kbd "C-u") nil)
    (define-key universal-argument-map (kbd "C-f") 'universal-argument-more)
  #+END_SRC
** Evil mode itself
   #+BEGIN_SRC emacs-lisp
     (use-package evil
       :init
       (setq evil-want-keybinding nil
             evil-want-C-u-scroll t
             evil-undo-system 'undo-fu) ;; Dependency is installed under * Basics.
       :config
       (evil-mode 1)
       (define-key evil-motion-state-map (kbd "C-f") nil)) ;; Unbind C-f that we use as comand prefix (bound above).
   #+END_SRC
** Evil Emacs key bindings
   #+BEGIN_SRC emacs-lisp
     ;; set leader key in all states
     (evil-set-leader nil (kbd "C-SPC"))
     ;; set leader key in specific states
     (evil-set-leader 'normal (kbd "SPC"))
     (evil-set-leader 'visual (kbd "SPC"))
     (evil-set-leader 'insert (kbd "C-SPC"))

     (evil-global-set-key 'normal (kbd "gl") 'evil-end-of-line)
     (evil-global-set-key 'normal (kbd "gh") 'evil-beginning-of-line)
     (evil-global-set-key 'normal (kbd "gj") 'end-of-buffer)
     (evil-global-set-key 'normal (kbd "gk") 'beginning-of-buffer)
     (evil-global-set-key 'normal (kbd "ga") 'evil-switch-to-windows-last-buffer)
     (evil-global-set-key 'normal (kbd "<leader>xs") 'save-buffer)
     (evil-global-set-key 'normal (kbd "<leader>xc") 'save-buffers-kill-terminal)
     (evil-global-set-key 'normal (kbd "<leader>r") 'replace-string)
     (evil-global-set-key 'visual (kbd "<leader>r") 'replace-string)
   #+END_SRC
*** Window management
#+BEGIN_SRC emacs-lisp
  (evil-global-set-key 'normal (kbd "<leader>w+") 'evil-window-increase-height)
  (evil-global-set-key 'normal (kbd "<leader>w-") 'evil-window-decrease-height)
  (evil-global-set-key 'normal (kbd "<leader>w<") 'evil-window-decrease-width)
  (evil-global-set-key 'normal (kbd "<leader>w>") 'evil-window-increase-width)
  (evil-global-set-key 'normal (kbd "<leader>ws") 'evil-window-vsplit)
  (evil-global-set-key 'normal (kbd "<leader>wv") 'evil-window-split)
  (evil-global-set-key 'normal (kbd "<leader>wh") 'evil-window-left)
  (evil-global-set-key 'normal (kbd "<leader>wj") 'evil-window-down)
  (evil-global-set-key 'normal (kbd "<leader>wk") 'evil-window-up)
  (evil-global-set-key 'normal (kbd "<leader>wl") 'evil-window-right)
  (evil-global-set-key 'normal (kbd "<leader>wH") 'evil-window-move-far-left)
  (evil-global-set-key 'normal (kbd "<leader>wJ") 'evil-window-move-very-bottom)
  (evil-global-set-key 'normal (kbd "<leader>wK") 'evil-window-move-very-top)
  (evil-global-set-key 'normal (kbd "<leader>wL") 'evil-window-move-far-right)
  (evil-global-set-key 'normal (kbd "<leader>wn") 'evil-window-new)
  (evil-global-set-key 'normal (kbd "<leader>wr") 'evil-window-rotate-downwards)
  (evil-global-set-key 'normal (kbd "<leader>wR") 'evil-window-rotate-upwards)
  (evil-global-set-key 'normal (kbd "<leader>wu") 'winner-undo)
  (evil-global-set-key 'normal (kbd "<leader>wU") 'winner-red)
  (evil-global-set-key 'normal (kbd "<leader>w1") 'delete-other-windows)
  (evil-global-set-key 'normal (kbd "<leader>w0") 'delete-window)
  (evil-global-set-key 'normal (kbd "<leader>wc") 'delete-window)
#+END_SRC
** Use evil-collection to have evil-bindings in other packages like magit.
#+BEGIN_SRC emacs-lisp
  (use-package evil-collection
    :after evil
    :config
    (evil-collection-init))
#+END_SRC
** Use evil-org to have evil-bindings in org-mode.
#+BEGIN_SRC emacs-lisp
  (use-package evil-org
    :after org
    :hook (org-mode . (lambda () evil-org-mode))
    :config
    (require 'evil-org-agenda)
    (evil-org-agenda-set-keys))
#+END_SRC

* Org, Org-Roam, and productivity
** Org
   The built-in version of Org is outdated and not sufficient for Org-Roam.
   Thanks to the straight package manager, we can use a simple ~use-package~ and straight will replace the built-in version with the latest version from ELPA.
   However, we must load org already in ~init.el~ in order to load the package before it is used to load this file.

   For org, use ~indented~ to show sub-items indented instead of all the leading asterisks.
   Hide emphasis markers and only use font face change as indication.

   Org-super-agenda and org-ql do not support tag groups. So it doesn't make sense to set them up.
   #+BEGIN_SRC emacs-lisp
     (setq org-startup-indented t
           org-pretty-entities t
           org-hide-emphasis-markers t
           org-startup-with-inline-images t
           org-image-acual-width '(300))
     (setq org-todo-keywords '((type "TODO(t)" "WAITING(w)" "FOLLOWUP(f)" "|" "DONE(d)" "DELEGATED(l)" "ABANDONED(a)")))
     (setq org-agenda-files (directory-files-recursively "~/Documents/org/" "\\.org$"))
   #+END_SRC

   Use org-appear to show emphasis-markers, which are hidden otherwise, when the cursor is on them.
   #+BEGIN_SRC emacs-lisp
       (use-package org-appear
         :hook (org-mode . org-appear-mode))
   #+END_SRC
   Use org-superstar to make the bullets look nicer.
   #+BEGIN_SRC emacs-lisp
     (use-package org-superstar
       :config
       (add-hook 'org-mode-hook (lambda () (org-superstar-mode 1))))
   #+END_SRC
** Org Keybindings
#+BEGIN_SRC emacs-lisp
  (evil-global-set-key 'normal (kbd "<leader>oa") 'org-agenda)
  (evil-define-key nil org-mode-map (kbd "<leader>ot") 'org-todo)
  (evil-define-key nil org-mode-map (kbd "<leader>og") 'org-set-tags-command)
#+END_SRC
** Org-QL
   Org query language to build agenda-like views based on an input query.
   #+BEGIN_SRC emacs-lisp
     (use-package org-ql)
   #+END_SRC
** Org-Super-Agenda
   Org super agenda groups agendas into groups based on its configuration.
   All groups must be configured here using the project's syntax.
   Super agenda does not support tag groups, that's why we have to list *all* relevant tags.
   #+BEGIN_SRC emacs-lisp
     (use-package org-super-agenda
       :config
       (setq org-super-agenda-groups '(
                                       (:name "Today"
                                        :scheduled today
                                        :scheduled past
                                        :deadline today
                                        :deadline past)
                                       (:name "Futurice"
                                        :and (:tag "futurice"
                                        :not (:todo ("WAITING" "FOLLOWUP"))))
                                       (:name "Private"
                                        :and (:tag "private"
                                        :not (:todo ("WAITING" "FOLLOWUP"))))
                                       (:name "Follow-up"
                                        :todo "FOLLOWUP")
                                       (:name "Waiting"
                                        :todo "WAITING"))))
     (org-super-agenda-mode)
   #+End_SRC
** Org-Roam
   Use ~<leader>wu~ and ~<leader>wU~ to go back and forth in the windows (bound earlier).
   #+BEGIN_SRC emacs-lisp
      (use-package org-roam
        :config
        (setq org-roam-directory (file-truename "~/Documents/org")
      	org-roam-dailies-directory "daily/"
      	org-roam-dailies-capture-templates
      	'(("d" "default" entry
      	   "* %?"
      	   :target (file+head "%<%Y-%m-%d>.org"
      			      "#+title: %<%Y-%m-%d>\n"))))
        (org-roam-db-autosync-mode)
        (add-to-list 'display-buffer-alist
      	     '("\\*org-roam\\*"
      	       (display-buffer-in-direction)
      	       (direction . right)
      	       (window-width . 0.33)
      	       (window-height . fit-window-to-buffer))))
      (evil-global-set-key 'normal (kbd "<leader>oi") 'org-roam-node-insert)
      (evil-global-set-key 'insert (kbd "<leader>oi") 'org-roam-node-insert)
      (evil-global-set-key 'normal (kbd "<leader>oi") 'org-roam-id-get-create)
      (evil-global-set-key 'insert (kbd "<leader>oi") 'org-roam-id-get-create)
      (evil-global-set-key 'normal (kbd "<leader>of") 'org-roam-node-find)
      (evil-global-set-key 'normal (kbd "<leader>oc") 'org-roam-capture)
      (evil-global-set-key 'normal (kbd "<leader>ob") 'org-roam-buffer-toggle)
      (evil-global-set-key 'insert (kbd "<leader>ob") 'org-roam-buffer-toggle)
      (evil-global-set-key 'normal (kbd "<leader>ol") 'org-roam-alias-add)
      (evil-global-set-key 'insert (kbd "<leader>ol") 'org-roam-alias-add)
      (evil-global-set-key 'normal (kbd "<leader>or") 'org-roam-ref-add)
      (evil-global-set-key 'insert (kbd "<leader>or") 'org-roam-ref-add)
      (evil-global-set-key 'normal (kbd "<leader>oj") 'org-roam-dailies-goto-today)
   #+END_SRC
** Deft
   Show and filter org-roam notes by contained text.
   #+BEGIN_SRC emacs-lisp
     (use-package deft
       :after org
       :custom
       (deft-recursive t)
       (deft-use-filter-string-for-filename t)
       (deft-use-filename-as-title t)
       (deft-default-extension "org")
       (deft-directory org-roam-directory)
       (deft-strip-summary-regexp ":PROPERTIES:\n\\(.+\n\\)+:END:\n"))
     (evil-global-set-key 'normal (kbd "<leader>od") 'deft)
   #+END_SRC
* Help
  Show all available key-bindings in the mini buffer.
  #+BEGIN_SRC emacs-lisp
    (use-package which-key
      :config
      (which-key-mode))
  #+END_SRC

  Company for auto-completion.
  #+BEGIN_SRC emacs-lisp
    (use-package company
      :config
      (setq company-idle-delay 0
	    company-minimum-prefix-length 4
	    company-selection-wrap-around t))
    (add-hook 'after-init-hook 'global-company-mode)
  #+END_SRC

* Visuals
** Window
  Remove startup message, tool bar, menu bar, and scroll bar.
  #+BEGIN_SRC emacs-lisp
    (setq inhibit-startup-message t)
    (tool-bar-mode -1)
    (menu-bar-mode -1)
    (scroll-bar-mode -1)
  #+END_SRC

** Fonts
Set a default font for all windows.
#+BEGIN_SRC emacs-lisp
  (set-frame-font "DejaVuSansMono Nerd Font Mono 11" nil t)
#+END_SRC
Show whitespaces everywhere
#+BEGIN_SRC emacs-lisp
  (global-whitespace-mode 1)
#+END_SRC

*** TODO Use a variable pitch (non-monospaced) font for org-mode, but not for code blocks inside org.

** Theme
   #+BEGIN_SRC emacs-lisp
     (use-package nord-theme
       :config
       (load-theme 'nord t))
   #+END_SRC

** Mode Line
  Modeline that looks like power line.
  #+BEGIN_SRC emacs-lisp
    (use-package powerline
      :config
      (powerline-default-theme))
    (setq column-number-mode t)
  #+END_SRC

* IDE Features
  Counsel, Ivy, and Swipe for more complete completion and filtering.
  #+BEGIN_SRC emacs-lisp
    (use-package counsel
      :config
      (ivy-mode 1)
      (counsel-mode 1)
      (setq ivy-use-virtual-buffers t
            ivy-count-format "(%d/%d) "
            ivy-re-builders-alist
          '((t . ivy--regex-ignore-order)))
      (evil-global-set-key 'normal (kbd "<leader>s") 'swiper-isearch)
      (evil-global-set-key 'normal (kbd "/") 'swiper-isearch)
      (evil-global-set-key 'normal (kbd "<leader>c") 'counsel-M-x)
      (evil-global-set-key 'insert (kbd "<leader>c") 'counsel-M-x)
      (evil-global-set-key 'normal (kbd "<leader>xf") 'counsel-find-file)
      (evil-global-set-key 'normal (kbd "<leader>y") 'counsel-yank-pop)
      (evil-global-set-key 'normal (kbd "<leader>Y") 'clipboard-yank)
      (evil-global-set-key 'insert (kbd "<leader>Y") 'clipboard-yank)
      (evil-global-set-key 'normal (kbd "<leader>xb") 'ivy-switch-buffer)
      (evil-global-set-key 'normal (kbd "<leader>v") 'ivy-push-view)
      (evil-global-set-key 'normal (kbd "<leader>V") 'ivy-pop-view)
      (evil-global-set-key 'normal (kbd "<leader>g") 'counsel-rg)
      (evil-global-set-key 'normal (kbd "<leader>a") 'counsel-linux-app)
      (evil-global-set-key 'normal (kbd "<leader>ff") 'counsel-fzf)
      (evil-global-set-key 'normal (kbd "<leader>xl") 'counsel-locate)
      (evil-global-set-key 'normal (kbd "<leader>xF") 'counsel-file-jump)
      (evil-global-set-key 'normal (kbd "<leader>xr") 'ivy-resume)
      (evil-global-set-key 'normal (kbd "<leader>b") 'counsel-bookmark)
      (evil-global-set-key 'normal (kbd "<leader>oo") 'counsel-outline))
  #+END_SRC

  Projectile for project navigation.
  #+BEGIN_SRC emacs-lisp
    (use-package projectile
      :config
      (projectile-mode +1)
      (evil-define-key 'normal projectile-mode-map (kbd "<leader>p") 'projectile-command-map))

    (use-package counsel-projectile
      :config
      (counsel-projectile-mode 1))
  #+END_SRC

  Magit for git integration.
  #+BEGIN_SRC emacs-lisp
    (use-package magit)
    (evil-global-set-key 'normal (kbd "<leader>t") 'magit-status)
  #+END_SRC

* Programming
  #+BEGIN_SRC emacs-lisp
    ;; Add line numbers in all programming modes.
    (add-hook 'prog-mode-hook 'display-line-numbers-mode)

    ;; Highlight numerals
    (use-package highlight-numbers
      :config
      (add-hook 'prog-mode-hook 'highlight-numbers-mode))

    ;; flycheck for all languages to do diagnostics in-line.
    (use-package flycheck
      :init (global-flycheck-mode))

    ;; YAML
    (use-package yaml-mode)

    ;; Web Mode for all things web.
    (use-package web-mode)

    ;; TypeScript
    (use-package tide
      :after (typescript-mode company flycheck)
      :hook ((typescript-mode . tide-setup)
             (typescript-mode . tide-hl-identifier-mode)
             (before-save . tide-format-before-save))
      :config (evil-collection-define-key 'normal 'tide-mode-map "gr" 'tide-references))
    ;; TSX
    (require 'web-mode)
    (add-to-list 'auto-mode-alist '("\\.tsx\\'" . web-mode))
    (add-hook 'web-mode-hook
              (lambda ()
                (when (string-equal "tsx" (file-name-extension buffer-file-name))
                  (setup-tide-mode))))
    ;; enable typescript-tslint checker
    (flycheck-add-mode 'typescript-tslint 'web-mode)
  #+END_SRC
  
