---
common_packages:
  - acpi
  - arandr
  - arc-theme
  - aspell
  - aspell-en
  - aspell-de
  - bat
  - blueman
  - bottom
  - brightnessctl
  - curl
  - dex-autostart
  - direnv
  - dunst
  - emacs
  - evince
  - evince-previewer
  - exa
  - fd-find
  - feh
  - flameshot
  - fwupd
  - fzf
  - git-delta
  - gnome-keyring
  - gscan2pdf
  - i3lock
  - i3status
  - ImageMagick
  - iw
  - jq
  - kak-lsp
  - kakoune
  - kitty
  - libsecret
  - libtool
  - lxappearance
  - maim
  - mopidy
  - mopidy-mpd
  - mopidy-spotify
  - NetworkManager
  - NetworkManager-openvpn
  - NetworkManager-tui
  - network-manager-applet
  - openvpn
  - papirus-icon-theme
  - pavucontrol
  - pdfarranger
  - picom
  - polybar
  - procs
  - python
  - python3-tkinter
  - qalculate-gtk
  - ranger
  - redshift
  - redshift-gtk
  - ripgrep
  - roboto-fontface-fonts
  - rofi
  - seahorse
  - tealdeer
  - thunar
  - tig
  - tlp
  - tmux
  - vlc
  - xbacklight
  - xclip
  - xdotool
  - xfce4-power-manager
  - xinput
  - xmodmap
  - xrdb
  - xset
  - xss-lock
  - zoxide
  - zsh
