[colors]
ansi = [
  '#2D2B37',
  '#BF7789',
  '#659774',
  '#9D8C30',
  '#6292AD',
  '#8884CB',
  '#519897',
  '#878794',
]
background = '#191724'
brights = [
  '#7C7992',
  '#BF7789',
  '#659774',
  '#9D8C30',
  '#6292AD',
  '#8884CB',
  '#519897',
  '#878794',
]
compose_cursor = '#B079AD'
cursor_bg = '#8884CB'
cursor_border = '#8884CB'
cursor_fg = '#0B0A0F'
foreground = '#8A8A9E'
scrollbar_thumb = '#7C7992'
selection_bg = '#2D2B37'
selection_fg = '#8A8A9E'
split = '#84848C'
visual_bell = '#2D2B37'

[colors.indexed]
16 = '#AB8465'
17 = '#B079AD'

[colors.tab_bar]
background = '#0B0A0F'
inactive_tab_edge = '#2D2B37'

[colors.tab_bar.active_tab]
bg_color = '#8884CB'
fg_color = '#0B0A0F'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#0B0A0F'
fg_color = '#8A8A9E'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#191724'
fg_color = '#8A8A9E'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#2D2B37'
fg_color = '#8A8A9E'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#2D2B37'
fg_color = '#8A8A9E'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'schemar'
name = 'Blueberry Peach Dark'
