[[manager.prepend_keymap]]
on = ["F"]
# See in plugins directory:
run = "plugin layout-tree-only"

# Open or enter, both with `l` key.
# See in plugins directory and https://github.com/yazi-rs/plugins/tree/main/smart-enter.yazi.
[[manager.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

# When you press `o` on a file, open it in helix in the "other" tmux pane.
# If you have yazi open in on tmux pane and helix in the other, you can use
# `o` to open the file under hover in the helix session in the other tmux
# pane.
# `.+` denotes the "next pane" in tmux.
[[manager.prepend_keymap]]
on = "o"
run = """
  shell 'tmux send-keys -t .+ ":open $0" C-m; tmux select-pane -t .+'
"""
