client.focused $bp_violet $bp_background $bp_text $bp_pink $bp_violet
client.focused_inactive $bp_overlay0 $bp_surface0 $bp_subtext $bp_surface1 $bp_surface1
client.unfocused $bp_surface0 $bp_surface0 $bp_subtext $bp_surface1 $bp_surface1
client.urgent $bp_red $bp_orange $bp_background $bp_orange $bp_red
client.placeholder #000000 $bp_background $bp_text #000000 #000000
client.background $bp_background
