theme = "catppuccin_latte"

[editor]
line-number = "absolute"
cursorline = true
# Required, as helix does not identify true-color support in tmux:
true-color = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
