[language-server.efm]
command = "efm-langserver"
config.documentFormatting = true

[language-server.godot]
command = "nc" 
args = [ "127.0.0.1", "6005"]

[[language]]
name = "typescript"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = ["format"] },
  { name = "efm" },
]

[[language]]
name = "gdscript"
language-servers = [ "godot" , "efm"]
