version: 2
root-markers:
  - .git/

tools:
  eslint: &eslint
    lint-command: >
      eslint_d -f visualstudio --stdin --stdin-filename ${INPUT}
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"
    require-marker: false
    root-markers:
      - .eslintrc
      - .eslintrc.js

  eslint-format: &eslint-format
    format-command: >
      eslint_d --stdin --fix-to-stdout --stdin-filename ${INPUT}
    format-stdin: true
    require-marker: false
    root-markers:
      - .eslintrc
      - .eslintrc.js

  prettier: &prettier
    format-command: >
      npx prettier --stdin-filepath ${INPUT} ${--range-start=charStart} ${--range-end=charEnd} \
        ${--tab-width=tabSize}
    format-stdin: true
    require-marker: false
    root-markers:
      - .prettierrc
      - .prettierrc.json
      - .prettierrc.js
      - .prettierrc.yml
      - .prettierrc.yaml
      - .prettierrc.json5
      - .prettierrc.mjs
      - .prettierrc.cjs
      - .prettierrc.toml

  stylua: &stylua
    format-command: >
      stylua --color Never ${--range-start:charStart} ${--range-end:charEnd} -
    format-stdin: true
    require-marker: false
    root-markers:
      - stylua.toml
      - .stylua.toml

languages:
  javascript:
    # Order is important (prettier first formats last)
    - <<: *prettier
    - <<: *eslint-format
    - <<: *eslint
  lua:
    - <<: *stylua
  typescript:
    # Order is important
    - <<: *prettier
    - <<: *eslint-format
    - <<: *eslint
